#ifndef QR2MATLABSTRUCT_IDL
#define QR2MATLABSTRUCT_IDL

#define MAX_STRING_LENGTH 50

module QR2matlab {


    struct timestamp
    {
        unsigned long sec;
        unsigned long usec;
    };

    struct std_msgs__Header
    {
        unsigned long seq;
        timestamp stamp;
    };

    struct std_msgs__String {
        string<MAX_STRING_LENGTH> data;
    };

    struct std_msgs__Seq_String {
        sequence<string<MAX_STRING_LENGTH> > data;
    };

    struct std_msgs__Stamped {
        std_msgs__Header header;
        std_msgs__String message;
    };

    struct std_msgs__Seq_Stamped {
        std_msgs__Header header;
        std_msgs__Seq_String message;
    };

#pragma masquerade ros std_msgs__String std_msgs/String
};
#endif /* QR2MATLABSTRUCT_IDL */

